---
title: "david_popomics_group_information"
author: "dbr314"
date: "2026-09-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Project update from ya boi


# week beginning

14.09.26

# Work achieved

Methodology document ordered in relation to results

Accurate sample map with scale bars and location in UK map inset 

Additional work re-formatting graphs and figures for the final thesis

# Problems

no problems


# Future work

Some minor changes to results, including manhattan plots focusing on chr_7 instead of chr_1 and the removal of DNA damaged samples from some additional graphs 



# week beginning

21.09.26


# Work achieved

Github repo created and synced with local machine containing all bash and r code for the project to this date

Thetas and Tajima D run for just modern day bro_lyn and data added to existing boxplots 

Plotting ngsadmix results

Previous week meeting edits made to graphs and figures


# Problems

fst job failed due to lack of memory
fst job failed due to error 134 (disk quota space for the project ran out??)


# Future work

writing up the methodology for fieldwork and labwork

Resume editting introduction and have method section + result fully formated by next week meeting 

