---
title: "Heterozygosity_ROH_loopangsd_pipeline_methology"
author: "dbr314"
date: "2026-09-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## loopangsd pipeline in bash

# depth calculation

```bash
##We made a simple rule to pick the max and min depth filters, it's essentially +/- depth/2. Depth is obtained from the BEARCAVE log and rounded to the nearest integer. When the depth is #an odd number, we round depth/2 down to obtain the min depth, and up to obtain the max depth. Thus for a depth of 7:

min = 7 - (7/2 rounded down)
    = 7 - 3
    = 4

max = 7 + (7/2 rounded up)
    = 7 + 4
    = 11

###MIN AND MAX DEPTH FILTERS for samples

# list of total scaffolds to be analysed

scaf='/scratch/SCWF00035/BEARCAVE0/refgenomes/rVipBer3/autosomes.txt'

# reference genome fasta, note it needs to be indexed for angsd

ref='/scratch/SCWF00035/BEARCAVE0/refgenomes/rVipBer3/GCA_964194415.1_newheaders.fa'

#a file predefining the window positions, each one is then fed to angsd in a loop using the -r option

win='/scratch/SCWF00035/collab/adders/loopangsd/depth/rVipBer3_50kb_windows_autosomes.txt'


###slurm parallel script 


vim slurm_parallel2.sh

#!/usr/bin/env bash

#SBATCH --account=SCWF00035_a_barlow_33
#SBATCH --nodes=1
#SBATCH --ntasks=28
#SBATCH --mem=30G
#SBATCH --output=./%J.out
#SBATCH --error=./%J.err
#SBATCH --time=00-04:00

module purge
module load parallel
module load angsd/0.940

# Parallel will dynamically distribute the commands in the commands_file
# across all of the cores that were requested (ntasks)
# n tasks have to match the number of individuals involved in the calc otherwise it gets weird

commands_file=$1
parallel < ${commands_file}



###depth script 


vim loopangsd_depth.sh


#!/bin/bash --login


# script to run angsd in a loop, getting around the arbitatrary way it assigns window positions
# we also record if data is not collected for a given window
# call the script:

# bash loopangsd_het.sh $1 $2 $3 $4

# $1 is the path and filename of bam file to be analysed
# $2 is output file prefix
# $3 min read depth
# $4 max read depth

# 3 other files are used by the script...

# list of total scaffolds to be analysed

scaf='/scratch/SCWF00035/BEARCAVE0/refgenomes/rVipBer3/autosomes.txt'

#reference genome fasta, note it needs to be indexed for angsd

ref='/scratch/SCWF00035/BEARCAVE0/refgenomes/rVipBer3/GCA_964194415.1_newheaders.fa'

#a file predefining the window positions, each one is then fed to angsd in a loop using the -r option

win='/scratch/SCWF00035/collab/adders/loopangsd/depth/rVipBer3_50kb_windows_autosomes.txt'


# and here are some other variables
cpus=1  # no. threads for angsd
max_depth=33 # max depth considered for depth analysis

# Estimate depth per window using the doDepth function from angsd

while read line; do

# Run angsd -dodepth for each window
angsd -i $1 -doDepth 1 -r $line -P $cpus -out $2_$line -minMapQ 30 -minQ 30 -setMinDepthInd $3 -setMaxDepthInd $4 -maxDepth $max_depth -doCounts 1

# write to file
paste <(echo $line) $2_$line.depthSample >> $2.window.depth

# Remove outputs for this iteration
rm $2_$line.depthSample $2_$line.depthGlobal $2_$line.arg

done < $win

echo "loops done!"


###MAKE SURE THERE ARE NO HARD RETURNS IN THIS SCRIPT

### commands file generation 

vim commands_NFadders.txt 

bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2cn+S3-SVb091_ber_rVipBer3_7.20274.bam 2cn 3 8
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/nu0+S6-SVb163_ber_rVipBer3_21.14275.bam nu0 7 21
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2rd+S8-SVb229_ber_rVipBer3_17.84131.bam 2rd 6 18 
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/d79+S9-SVb230_ber_rVipBer3_14.86320.bam d79 5 15
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/6i5+S10-SVb271_ber_rVipBer3_13.22348.bam 6i5 5 14
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x1t+S11-SVb316_ber_rVipBer3_9.10306.bam x1t 3 9
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o8g+S12-SVb371_ber_rVipBer3_32.21524.bam o8g 11 33
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2sj+S13-SVb399_ber_rVipBer3_14.67941.bam 2sj 5 15
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/42r+S14-SVb410_ber_rVipBer3_21.13850.bam 42r 7 21
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/46y+S22_1895_ber_rVipBer3_7.58190.bam 46y 3 9
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/h9d+S24_1895_ber_rVipBer3_7.70202.bam h9d 3 9
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/rzt+S26_1895_ber_rVipBer3_9.42227.bam rzt 4 11
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/hpa+S28_1908_ber_rVipBer3_16.86980.bam hpa 6 17
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5h5+S29_1894_ber_rVipBer3_12.72974.bam 5h5 5 14
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/vyo+S30_1894_ber_rVipBer3_13.62265.bam vyo 5 15
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4w7+S31_1917_ber_rVipBer3_27.24751.bam 4w7 9 27
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5fu+S32_1917_ber_rVipBer3_29.72487.bam 5fu 10 30
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/me5+S33_1917_ber_rVipBer3_24.70592.bam me5 8 24
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/mnw+S34_1896_ber_rVipBer3_9.99212.bam mnw 4 11
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/gvw+S35_1896_ber_rVipBer3_15.11601.bam gvw 6 17
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/ivx_th6+ww6523_ber_rVipBer3_aln_9.39783.bam ivx 3 10
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o5k_bo6+ww6524_ber_rVipBer3_aln_9.25411.bam o5k 3 10
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4rs+ww6514_ber_rVipBer3_aln_21.72646.bam 4rs 7 22
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/eyL_xaw+ww6515_ber_rVipBer3_aln_9.40289.bam eyL 3 10
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x3v_a31+ww6516_ber_rVipBer3_aln_8.82775.bam x3v 3 10
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/qdL_c8p+ww6518_ber_rVipBer3_aln_9.40188.bam qdL 3 10
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/whu_wd3+ww6519_ber_rVipBer3_aln_9.09410.bam whu 3 10
bash loopangsd_depth.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o55+ww6522_ber_rVipBer3_aln_9.83417.bam o55 3 10
```

# site allele frequency calculation for each individual 

```bash
##saf for historic 

vim angsd_NFsaf.sh

#!/bin/bash
###
#SBATCH --account=SCWF00035_a_barlow_33
#SBATCH --job-name=saf_NFadders
#SBATCH --output=/scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans_saf/saf_nhm_out%J
#SBATCH --error=/scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans_saf/saf_nhm_err%J
#SBATCH --time=0-06:00
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --mem=6G

#load modules
module purge
module load angsd/0.935

# $1 is the path and filename of bam file to be analysed
# $2 is output file prefix
# $3 min read depth
# $4 max read depth

# list of total scaffolds to be analysed

scaf='/scratch/SCWF00035/BEARCAVE0/refgenomes/rVipBer3/autosomes.txt'

#reference genome fasta outgroup file, note it needs to be indexed for angsd

anc='/scratch/SCWF00035/collab/outgroups/ursinii_mapped_berus/9vi+L41_urs_rVipBer3.fa' 

# and here are some other variables

cpus=4	# no. threads for angsd

# estimate site allele frequency likelihood
# Note you only need to run this once on the whole genome, then proceed with loopangsd_het.sh etc

angsd -i $1 -noTrans 1 -trim 5 -doSaf 1 -GL 1 -P $cpus -anc $anc -rf $scaf -out $2 -minMapQ 30 -minQ 30 -setMinDepthInd $3 -setMaxDepthInd $4 -doCounts 1

echo "SAF done!"


##saf for modern day

vim angsd_mod_NFsaf.sh

#!/bin/bash
###
#SBATCH --account=SCWF00035_a_barlow_33
#SBATCH --job-name=saf_mod_NFadders
#SBATCH --output=/scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans_saf/saf_mod_out%J
#SBATCH --error=/scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans_saf/saf_mod_err%J
#SBATCH --time=0-12:00
#SBATCH --nodes=1
#SBATCH --ntasks=4
#SBATCH --mem=6G

#load modules
module purge
module load angsd/0.935

# $1 is the path and filename of bam file to be analysed
# $2 is output file prefix
# $3 min read depth
# $4 max read depth

# list of total scaffolds to be analysed

scaf='/scratch/SCWF00035/BEARCAVE0/refgenomes/rVipBer3/autosomes.txt'

#reference genome fasta outgroup file, note it needs to be indexed for angsd

anc='/scratch/SCWF00035/collab/outgroups/ursinii_mapped_berus/9vi+L41_urs_rVipBer3.fa' 

# and here are some other variables

cpus=4	# no. threads for angsd

# estimate site allele frequency likelihood
# Note you only need to run this once on the whole genome, then proceed with loopangsd_het.sh etc

angsd -i $1 -noTrans 1 -doSaf 1 -GL 1 -P $cpus -anc $anc -rf $scaf -out $2 -minMapQ 30 -minQ 30 -setMinDepthInd $3 -setMaxDepthInd $4 -doCounts 1

echo "SAF done!"


##slurm script that calls on the "angsd_NFsaf.sh" script and applies processes to each sample for the historic samples 


vim saf_NFadders.sh

#!/bin/bash --login
###
#account
#SBATCH --account=SCWF00035_a_barlow_33
#job name
#SBATCH --job-name=safi
#job stdout file
#SBATCH --output=./saf_out%J
#job stderr file
#SBATCH --error=./saf_err%J
#maximum job time in D-HH:MM
#SBATCH --time=0-06:00
#number of nodes
#SBATCH --nodes=1
#number of parallel processes (tasks)
#SBATCH --ntasks=4
#memory in Gb
#SBATCH --mem=6G

#load modules used by the script
module purge
module load angsd/0.935

# bash loopangsd_het.sh $1 $2 $3 $4

# $1 is the path and filename of bam file to be analysed
# $2 is output file prefix
# $3 min read depth
# $4 max read depth

bash angsd_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/46y+S22_1895_ber_rVipBer3_7.58190.bam 46y 3 9
bash angsd_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/h9d+S24_1895_ber_rVipBer3_7.70202.bam h9d 3 9
bash angsd_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/rzt+S26_1895_ber_rVipBer3_9.42227.bam rzt 4 11
bash angsd_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/hpa+S28_1908_ber_rVipBer3_16.86980.bam hpa 6 17
bash angsd_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5h5+S29_1894_ber_rVipBer3_12.72974.bam 5h5 5 14
bash angsd_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/vyo+S30_1894_ber_rVipBer3_13.62265.bam vyo 5 15
bash angsd_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4w7+S31_1917_ber_rVipBer3_27.24751.bam 4w7 9 27
bash angsd_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5fu+S32_1917_ber_rVipBer3_29.72487.bam 5fu 10 30
bash angsd_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/me5+S33_1917_ber_rVipBer3_24.70592.bam me5 8 24
bash angsd_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/mnw+S34_1896_ber_rVipBer3_9.99212.bam mnw 4 11
bash angsd_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/gvw+S35_1896_ber_rVipBer3_15.11601.bam gvw 6 17


####slurm script that calls on the "angsd_mod_NFsaf.sh" script and applies processes to each sample for the modern day samples 

vim saf_mod_NFadders.sh

#!/bin/bash --login
###
#account
#SBATCH --account=SCWF00035_a_barlow_33
#job name
#SBATCH --job-name=safi_mod
#job stdout file
#SBATCH --output=./saf_mod_out%J
#job stderr file
#SBATCH --error=./saf_mod_err%J
#maximum job time in D-HH:MM
#SBATCH --time=0-12:00
#number of nodes
#SBATCH --nodes=1
#number of parallel processes (tasks)
#SBATCH --ntasks=4
#memory in Gb
#SBATCH --mem=6G

#load modules used by the script
module purge
module load angsd/0.935

# bash loopangsd_het.sh $1 $2 $3 $4

# $1 is the path and filename of bam file to be analysed
# $2 is output file prefix
# $3 min read depth
# $4 max read depth

bash angsd_mod_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2cn+S3-SVb091_ber_rVipBer3_7.20274.bam 2cn 3 8
bash angsd_mod_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/nu0+S6-SVb163_ber_rVipBer3_21.14275.bam nu0 7 21
bash angsd_mod_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2rd+S8-SVb229_ber_rVipBer3_17.84131.bam 2rd 6 18 
bash angsd_mod_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/d79+S9-SVb230_ber_rVipBer3_14.86320.bam d79 5 15
bash angsd_mod_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/6i5+S10-SVb271_ber_rVipBer3_13.22348.bam 6i5 5 14
bash angsd_mod_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x1t+S11-SVb316_ber_rVipBer3_9.10306.bam x1t 3 9
bash angsd_mod_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o8g+S12-SVb371_ber_rVipBer3_32.21524.bam o8g 11 33
bash angsd_mod_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2sj+S13-SVb399_ber_rVipBer3_14.67941.bam 2sj 5 15
bash angsd_mod_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/42r+S14-SVb410_ber_rVipBer3_21.13850.bam 42r 7 21
bash angsd_mod_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3/ivx_th6+ww6523_ber_rVipBer3_10.11033.bam ivx 3 10
bash angsd_mod_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3/o5k_bo6+ww6524_ber_rVipBer3_9.93584.bam o5k 3 10
bash angsd_mod_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3/4rs+ww6514_ber_rVipBer3_23.24245.bam 4rs 8 23
bash angsd_mod_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3/eyL_xaw+ww6515_ber_rVipBer3_10.18655.bam eyL 3 10
bash angsd_mod_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3/x3v_a31+ww6516_ber_rVipBer3_9.50278.bam x3v 3 10
bash angsd_mod_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3/qdL_c8p+ww6518_ber_rVipBer3_10.22644.bam qdL 4 11
bash angsd_mod_NFsaf.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3/whu_wd3+ww6519_ber_rVipBer3_9.79933.bam whu 3 10
```

# Heterozygosity sfs file generation for each sample

```bash
vim slurm_parallel2_chr.sh

#!/usr/bin/env bash

#SBATCH --account=SCWF00035_a_barlow_33
#SBATCH --nodes=1
#SBATCH --ntasks=28
#SBATCH --mem=32G
#SBATCH --output=./logs/%J.out
#SBATCH --error=./logs/%J.err
#SBATCH --time=01-15:00

module purge
module load parallel
module load angsd/0.935

# Parallel will dynamically distribute the commands in the commands_file
# across all of the cores that were requested (ntasks)
commands_file=$1
parallel < ${commands_file}


#het script copied from collab using 

cp -a /scratch/SCWF00035/collab/adders/loopangsd/het_chr/loopangsd_het_chr2.sh . /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het 

#this copies everything within the source directory and then I have to delete a bunch of stuff

rm -r 

#deletes folder with everything in it, use wisely 


###het script

vim loopangsd_het_chr2.sh

#!/bin/bash --login
#SBATCH --account=SCWF00035_a_barlow_33

# script to run angsd in a loop, getting around the arbitrary way it assigns window positions
# we also record if data is not collected for a given window

# note you need to have calculated the SAF in advance using angsd, and have the file prefixes matching those used here
# The idea is you use this script on individual chr, and process multiple individals simultaneously using parallel

# call the script:

# $1 is the path and filename of bam file to be analysed
# $2 is output file prefix
# $3 is path and file predefining the window positions
# $4 is output folder (omit trailing/)

# and here are some other variables

saf='/scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans_saf'	
# path to precalculated SAF files

cpus=1			

# no. threads for angsd

# get rid of any existing file
rm $4/$2.window.sfs

# Loop through windows and calculate sfs
# The output is the window position as shown above, followed by the sfs estimation

	while read line; do
		realSFS $saf/$2.saf.idx -r $line -P $cpus > $4/$2_$line.sfs
		paste <(echo $line) $4/$2_$line.sfs >> $4/$2.window.sfs
		rm $4/$2_$line.sfs
	done < $3

echo "loops done!"

##when running the parallel script on multiple chromosomes use

sbatch slurm_parallel2_chr.sh ./chr_1/commands_chr1.txt

#change the directory "chr_1" and "commands_chr1.tx" to reflect the different chr each time you run this command

# parallel commands in full

sbatch slurm_parallel2_chr.sh ./chr_1/commands_chr1.txt
sbatch slurm_parallel2_chr.sh ./chr_2/commands_chr2.txt
sbatch slurm_parallel2_chr.sh ./chr_3/commands_chr3.txt 
sbatch slurm_parallel2_chr.sh ./chr_4/commands_chr4.txt 
sbatch slurm_parallel2_chr.sh ./chr_5/commands_chr5.txt  
sbatch slurm_parallel2_chr.sh ./chr_6/commands_chr6.txt  
sbatch slurm_parallel2_chr.sh ./chr_7/commands_chr7.txt 
sbatch slurm_parallel2_chr.sh ./chr_8-17/commands_chr8-17.txt 

# when files have been generated 

# First generate a filein shell concatenating all chr for one individual, e.g.
# cat ./het_chr/chr_*/R06.window.sfs > R06_all.window.sfs
# The cat command is used to show the content of files in the terminal. You can also use it to combine multiple files into one

#cat commands for each individual 
 

vim cat_command.sh

cat ./het_rmtrans/chr_*/2cn.window.sfs > 2cn_all.window.sfs
cat ./het_rmtrans/chr_*/nu0.window.sfs > nu0_all.window.sfs 
cat ./het_rmtrans/chr_*/2rd.window.sfs > 2rd_all.window.sfs 
cat ./het_rmtrans/chr_*/d79.window.sfs > d79_all.window.sfs 
cat ./het_rmtrans/chr_*/6i5.window.sfs > 6i5_all.window.sfs 
cat ./het_rmtrans/chr_*/x1t.window.sfs > x1t_all.window.sfs 
cat ./het_rmtrans/chr_*/o8g.window.sfs > o8g_all.window.sfs 
cat ./het_rmtrans/chr_*/2sj.window.sfs > 2sj_all.window.sfs 
cat ./het_rmtrans/chr_*/42r.window.sfs > 42r_all.window.sfs 
cat ./het_rmtrans/chr_*/46y.window.sfs > 46y_all.window.sfs
cat ./het_rmtrans/chr_*/h9d.window.sfs > h9d_all.window.sfs 
cat ./het_rmtrans/chr_*/rzt.window.sfs > rzt_all.window.sfs 
cat ./het_rmtrans/chr_*/hpa.window.sfs > hpa_all.window.sfs 
cat ./het_rmtrans/chr_*/5h5.window.sfs > 5h5_all.window.sfs 
cat ./het_rmtrans/chr_*/vyo.window.sfs > vyo_all.window.sfs 
cat ./het_rmtrans/chr_*/4w7.window.sfs > 4w7_all.window.sfs 
cat ./het_rmtrans/chr_*/5fu.window.sfs > 5fu_all.window.sfs 
cat ./het_rmtrans/chr_*/me5.window.sfs > me5_all.window.sfs 
cat ./het_rmtrans/chr_*/mnw.window.sfs > mnw_all.window.sfs 
cat ./het_rmtrans/chr_*/gvw.window.sfs > gvw_all.window.sfs 
cat ./het_rmtrans/chr_*/ivx.window.sfs > ivx_all.window.sfs 
cat ./het_rmtrans/chr_*/o5k.window.sfs > o5k_all.window.sfs 
cat ./het_rmtrans/chr_*/4rs.window.sfs > 4rs_all.window.sfs 
cat ./het_rmtrans/chr_*/eyL.window.sfs > eyL_all.window.sfs 
cat ./het_rmtrans/chr_*/x3v.window.sfs > x3v_all.window.sfs 
cat ./het_rmtrans/chr_*/qdL.window.sfs > qdL_all.window.sfs 
cat ./het_rmtrans/chr_*/whu.window.sfs > whu_all.window.sfs 
cat ./het_rmtrans/chr_*/o55.window.sfs > o55_all.window.sfs 

bash cat_command.sh

#for the plotting of ROH and HET in R you require the .sfs files for each individual for each chr and the total .sfs files for each individual over all chr
```

# Heterozygosity sfs command file generation that applies sfs file generation scripts

```bash
###chr_1

vim commands_chr1.txt

bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2cn+S3-SVb091_ber_rVipBer3_7.20274.bam 2cn /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/nu0+S6-SVb163_ber_rVipBer3_21.14275.bam nu0 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2rd+S8-SVb229_ber_rVipBer3_17.84131.bam 2rd /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/d79+S9-SVb230_ber_rVipBer3_14.86320.bam d79 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/6i5+S10-SVb271_ber_rVipBer3_13.22348.bam 6i5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x1t+S11-SVb316_ber_rVipBer3_9.10306.bam x1t /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o8g+S12-SVb371_ber_rVipBer3_32.21524.bam o8g /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2sj+S13-SVb399_ber_rVipBer3_14.67941.bam 2sj /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/42r+S14-SVb410_ber_rVipBer3_21.13850.bam 42r /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/46y+S22_1895_ber_rVipBer3_7.58190.bam 46y /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/h9d+S24_1895_ber_rVipBer3_7.70202.bam h9d /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/rzt+S26_1895_ber_rVipBer3_9.42227.bam rzt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/hpa+S28_1908_ber_rVipBer3_16.86980.bam hpa /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5h5+S29_1894_ber_rVipBer3_12.72974.bam 5h5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/vyo+S30_1894_ber_rVipBer3_13.62265.bam vyo /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4w7+S31_1917_ber_rVipBer3_27.24751.bam 4w7 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5fu+S32_1917_ber_rVipBer3_29.72487.bam 5fu /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/me5+S33_1917_ber_rVipBer3_24.70592.bam me5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/mnw+S34_1896_ber_rVipBer3_9.99212.bam mnw /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/gvw+S35_1896_ber_rVipBer3_15.11601.bam gvw /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/ivx_th6+ww6523_ber_rVipBer3_aln_9.39783.bam ivx /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o5k_bo6+ww6524_ber_rVipBer3_aln_9.25411.bam o5k /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4rs+ww6514_ber_rVipBer3_aln_21.72646.bam 4rs /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/eyL_xaw+ww6515_ber_rVipBer3_aln_9.40289.bam eyL /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x3v_a31+ww6516_ber_rVipBer3_aln_8.82775.bam x3v /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/qdL_c8p+ww6518_ber_rVipBer3_aln_9.40188.bam qdL /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/whu_wd3+ww6519_ber_rVipBer3_aln_9.09410.bam whu /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o55+ww6522_ber_rVipBer3_aln_9.83417.bam o55 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1/chr_1_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_1



###chr_2

vim commands_chr2.txt


bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2cn+S3-SVb091_ber_rVipBer3_7.20274.bam 2cn /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2 
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/nu0+S6-SVb163_ber_rVipBer3_21.14275.bam nu0 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2rd+S8-SVb229_ber_rVipBer3_17.84131.bam 2rd /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/d79+S9-SVb230_ber_rVipBer3_14.86320.bam d79 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/6i5+S10-SVb271_ber_rVipBer3_13.22348.bam 6i5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x1t+S11-SVb316_ber_rVipBer3_9.10306.bam x1t /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o8g+S12-SVb371_ber_rVipBer3_32.21524.bam o8g /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2sj+S13-SVb399_ber_rVipBer3_14.67941.bam 2sj /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/42r+S14-SVb410_ber_rVipBer3_21.13850.bam 42r /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/46y+S22_1895_ber_rVipBer3_7.58190.bam 46y /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/h9d+S24_1895_ber_rVipBer3_7.70202.bam h9d /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/rzt+S26_1895_ber_rVipBer3_9.42227.bam rzt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/hpa+S28_1908_ber_rVipBer3_16.86980.bam hpa /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5h5+S29_1894_ber_rVipBer3_12.72974.bam 5h5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/vyo+S30_1894_ber_rVipBer3_13.62265.bam vyo /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4w7+S31_1917_ber_rVipBer3_27.24751.bam 4w7 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5fu+S32_1917_ber_rVipBer3_29.72487.bam 5fu /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/me5+S33_1917_ber_rVipBer3_24.70592.bam me5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/mnw+S34_1896_ber_rVipBer3_9.99212.bam mnw /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/gvw+S35_1896_ber_rVipBer3_15.11601.bam gvw /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/ivx_th6+ww6523_ber_rVipBer3_aln_9.39783.bam ivx /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o5k_bo6+ww6524_ber_rVipBer3_aln_9.25411.bam o5k /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4rs+ww6514_ber_rVipBer3_aln_21.72646.bam 4rs /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/eyL_xaw+ww6515_ber_rVipBer3_aln_9.40289.bam eyL /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x3v_a31+ww6516_ber_rVipBer3_aln_8.82775.bam x3v /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/qdL_c8p+ww6518_ber_rVipBer3_aln_9.40188.bam qdL /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/whu_wd3+ww6519_ber_rVipBer3_aln_9.09410.bam whu /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o55+ww6522_ber_rVipBer3_aln_9.83417.bam o55 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2/chr_2_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_2





###chr_3

vim commands_chr3.txt


bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2cn+S3-SVb091_ber_rVipBer3_7.20274.bam 2cn /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/nu0+S6-SVb163_ber_rVipBer3_21.14275.bam nu0 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2rd+S8-SVb229_ber_rVipBer3_17.84131.bam 2rd /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/d79+S9-SVb230_ber_rVipBer3_14.86320.bam d79 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/6i5+S10-SVb271_ber_rVipBer3_13.22348.bam 6i5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x1t+S11-SVb316_ber_rVipBer3_9.10306.bam x1t /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o8g+S12-SVb371_ber_rVipBer3_32.21524.bam o8g /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2sj+S13-SVb399_ber_rVipBer3_14.67941.bam 2sj /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/42r+S14-SVb410_ber_rVipBer3_21.13850.bam 42r /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/46y+S22_1895_ber_rVipBer3_7.58190.bam 46y /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/h9d+S24_1895_ber_rVipBer3_7.70202.bam h9d /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/rzt+S26_1895_ber_rVipBer3_9.42227.bam rzt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/hpa+S28_1908_ber_rVipBer3_16.86980.bam hpa /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5h5+S29_1894_ber_rVipBer3_12.72974.bam 5h5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/vyo+S30_1894_ber_rVipBer3_13.62265.bam vyo /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4w7+S31_1917_ber_rVipBer3_27.24751.bam 4w7 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5fu+S32_1917_ber_rVipBer3_29.72487.bam 5fu /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/me5+S33_1917_ber_rVipBer3_24.70592.bam me5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/mnw+S34_1896_ber_rVipBer3_9.99212.bam mnw /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/gvw+S35_1896_ber_rVipBer3_15.11601.bam gvw /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/ivx_th6+ww6523_ber_rVipBer3_aln_9.39783.bam ivx /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o5k_bo6+ww6524_ber_rVipBer3_aln_9.25411.bam o5k /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4rs+ww6514_ber_rVipBer3_aln_21.72646.bam 4rs /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/eyL_xaw+ww6515_ber_rVipBer3_aln_9.40289.bam eyL /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x3v_a31+ww6516_ber_rVipBer3_aln_8.82775.bam x3v /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/qdL_c8p+ww6518_ber_rVipBer3_aln_9.40188.bam qdL /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/whu_wd3+ww6519_ber_rVipBer3_aln_9.09410.bam whu /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o55+ww6522_ber_rVipBer3_aln_9.83417.bam o55 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3/chr_3_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_3






###chr_4

vim commands_chr4.txt


bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2cn+S3-SVb091_ber_rVipBer3_7.20274.bam 2cn /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/nu0+S6-SVb163_ber_rVipBer3_21.14275.bam nu0 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2rd+S8-SVb229_ber_rVipBer3_17.84131.bam 2rd /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/d79+S9-SVb230_ber_rVipBer3_14.86320.bam d79 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/6i5+S10-SVb271_ber_rVipBer3_13.22348.bam 6i5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x1t+S11-SVb316_ber_rVipBer3_9.10306.bam x1t /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o8g+S12-SVb371_ber_rVipBer3_32.21524.bam o8g /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2sj+S13-SVb399_ber_rVipBer3_14.67941.bam 2sj /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/42r+S14-SVb410_ber_rVipBer3_21.13850.bam 42r /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/46y+S22_1895_ber_rVipBer3_7.58190.bam 46y /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/h9d+S24_1895_ber_rVipBer3_7.70202.bam h9d /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/rzt+S26_1895_ber_rVipBer3_9.42227.bam rzt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/hpa+S28_1908_ber_rVipBer3_16.86980.bam hpa /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5h5+S29_1894_ber_rVipBer3_12.72974.bam 5h5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/vyo+S30_1894_ber_rVipBer3_13.62265.bam vyo /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4w7+S31_1917_ber_rVipBer3_27.24751.bam 4w7 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5fu+S32_1917_ber_rVipBer3_29.72487.bam 5fu /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/me5+S33_1917_ber_rVipBer3_24.70592.bam me5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/mnw+S34_1896_ber_rVipBer3_9.99212.bam mnw /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/gvw+S35_1896_ber_rVipBer3_15.11601.bam gvw /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/ivx_th6+ww6523_ber_rVipBer3_aln_9.39783.bam ivx /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o5k_bo6+ww6524_ber_rVipBer3_aln_9.25411.bam o5k /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4rs+ww6514_ber_rVipBer3_aln_21.72646.bam 4rs /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/eyL_xaw+ww6515_ber_rVipBer3_aln_9.40289.bam eyL /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x3v_a31+ww6516_ber_rVipBer3_aln_8.82775.bam x3v /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/qdL_c8p+ww6518_ber_rVipBer3_aln_9.40188.bam qdL /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/whu_wd3+ww6519_ber_rVipBer3_aln_9.09410.bam whu /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o55+ww6522_ber_rVipBer3_aln_9.83417.bam o55 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4/chr_4_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_4




###chr_5
 
vim commands_chr5.txt


bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2cn+S3-SVb091_ber_rVipBer3_7.20274.bam 2cn /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/nu0+S6-SVb163_ber_rVipBer3_21.14275.bam nu0 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2rd+S8-SVb229_ber_rVipBer3_17.84131.bam 2rd /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/d79+S9-SVb230_ber_rVipBer3_14.86320.bam d79 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/6i5+S10-SVb271_ber_rVipBer3_13.22348.bam 6i5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x1t+S11-SVb316_ber_rVipBer3_9.10306.bam x1t /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o8g+S12-SVb371_ber_rVipBer3_32.21524.bam o8g /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2sj+S13-SVb399_ber_rVipBer3_14.67941.bam 2sj /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/42r+S14-SVb410_ber_rVipBer3_21.13850.bam 42r /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/46y+S22_1895_ber_rVipBer3_7.58190.bam 46y /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/h9d+S24_1895_ber_rVipBer3_7.70202.bam h9d /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/rzt+S26_1895_ber_rVipBer3_9.42227.bam rzt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/hpa+S28_1908_ber_rVipBer3_16.86980.bam hpa /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5h5+S29_1894_ber_rVipBer3_12.72974.bam 5h5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/vyo+S30_1894_ber_rVipBer3_13.62265.bam vyo /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4w7+S31_1917_ber_rVipBer3_27.24751.bam 4w7 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5fu+S32_1917_ber_rVipBer3_29.72487.bam 5fu /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/me5+S33_1917_ber_rVipBer3_24.70592.bam me5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/mnw+S34_1896_ber_rVipBer3_9.99212.bam mnw /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/gvw+S35_1896_ber_rVipBer3_15.11601.bam gvw /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/ivx_th6+ww6523_ber_rVipBer3_aln_9.39783.bam ivx /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o5k_bo6+ww6524_ber_rVipBer3_aln_9.25411.bam o5k /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4rs+ww6514_ber_rVipBer3_aln_21.72646.bam 4rs /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/eyL_xaw+ww6515_ber_rVipBer3_aln_9.40289.bam eyL /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x3v_a31+ww6516_ber_rVipBer3_aln_8.82775.bam x3v /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/qdL_c8p+ww6518_ber_rVipBer3_aln_9.40188.bam qdL /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/whu_wd3+ww6519_ber_rVipBer3_aln_9.09410.bam whu /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o55+ww6522_ber_rVipBer3_aln_9.83417.bam o55 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5/chr_5_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_5



###chr_6

vim commands_chr6.txt



bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2cn+S3-SVb091_ber_rVipBer3_7.20274.bam 2cn /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/nu0+S6-SVb163_ber_rVipBer3_21.14275.bam nu0 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2rd+S8-SVb229_ber_rVipBer3_17.84131.bam 2rd /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/d79+S9-SVb230_ber_rVipBer3_14.86320.bam d79 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/6i5+S10-SVb271_ber_rVipBer3_13.22348.bam 6i5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x1t+S11-SVb316_ber_rVipBer3_9.10306.bam x1t /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o8g+S12-SVb371_ber_rVipBer3_32.21524.bam o8g /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2sj+S13-SVb399_ber_rVipBer3_14.67941.bam 2sj /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/42r+S14-SVb410_ber_rVipBer3_21.13850.bam 42r /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/46y+S22_1895_ber_rVipBer3_7.58190.bam 46y /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/h9d+S24_1895_ber_rVipBer3_7.70202.bam h9d /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/rzt+S26_1895_ber_rVipBer3_9.42227.bam rzt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/hpa+S28_1908_ber_rVipBer3_16.86980.bam hpa /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5h5+S29_1894_ber_rVipBer3_12.72974.bam 5h5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/vyo+S30_1894_ber_rVipBer3_13.62265.bam vyo /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4w7+S31_1917_ber_rVipBer3_27.24751.bam 4w7 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5fu+S32_1917_ber_rVipBer3_29.72487.bam 5fu /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/me5+S33_1917_ber_rVipBer3_24.70592.bam me5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/mnw+S34_1896_ber_rVipBer3_9.99212.bam mnw /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/gvw+S35_1896_ber_rVipBer3_15.11601.bam gvw /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/ivx_th6+ww6523_ber_rVipBer3_aln_9.39783.bam ivx /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o5k_bo6+ww6524_ber_rVipBer3_aln_9.25411.bam o5k /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4rs+ww6514_ber_rVipBer3_aln_21.72646.bam 4rs /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/eyL_xaw+ww6515_ber_rVipBer3_aln_9.40289.bam eyL /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x3v_a31+ww6516_ber_rVipBer3_aln_8.82775.bam x3v /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/qdL_c8p+ww6518_ber_rVipBer3_aln_9.40188.bam qdL /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/whu_wd3+ww6519_ber_rVipBer3_aln_9.09410.bam whu /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o55+ww6522_ber_rVipBer3_aln_9.83417.bam o55 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6/chr_6_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_6


###chr_7

vim commands_chr7.txt


bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2cn+S3-SVb091_ber_rVipBer3_7.20274.bam 2cn /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/nu0+S6-SVb163_ber_rVipBer3_21.14275.bam nu0 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2rd+S8-SVb229_ber_rVipBer3_17.84131.bam 2rd /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/d79+S9-SVb230_ber_rVipBer3_14.86320.bam d79 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/6i5+S10-SVb271_ber_rVipBer3_13.22348.bam 6i5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x1t+S11-SVb316_ber_rVipBer3_9.10306.bam x1t /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o8g+S12-SVb371_ber_rVipBer3_32.21524.bam o8g /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2sj+S13-SVb399_ber_rVipBer3_14.67941.bam 2sj /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/42r+S14-SVb410_ber_rVipBer3_21.13850.bam 42r /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/46y+S22_1895_ber_rVipBer3_7.58190.bam 46y /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/h9d+S24_1895_ber_rVipBer3_7.70202.bam h9d /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/rzt+S26_1895_ber_rVipBer3_9.42227.bam rzt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/hpa+S28_1908_ber_rVipBer3_16.86980.bam hpa /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5h5+S29_1894_ber_rVipBer3_12.72974.bam 5h5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/vyo+S30_1894_ber_rVipBer3_13.62265.bam vyo /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4w7+S31_1917_ber_rVipBer3_27.24751.bam 4w7 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5fu+S32_1917_ber_rVipBer3_29.72487.bam 5fu /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/me5+S33_1917_ber_rVipBer3_24.70592.bam me5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/mnw+S34_1896_ber_rVipBer3_9.99212.bam mnw /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/gvw+S35_1896_ber_rVipBer3_15.11601.bam gvw /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/ivx_th6+ww6523_ber_rVipBer3_aln_9.39783.bam ivx /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o5k_bo6+ww6524_ber_rVipBer3_aln_9.25411.bam o5k /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4rs+ww6514_ber_rVipBer3_aln_21.72646.bam 4rs /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/eyL_xaw+ww6515_ber_rVipBer3_aln_9.40289.bam eyL /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x3v_a31+ww6516_ber_rVipBer3_aln_8.82775.bam x3v /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/qdL_c8p+ww6518_ber_rVipBer3_aln_9.40188.bam qdL /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/whu_wd3+ww6519_ber_rVipBer3_aln_9.09410.bam whu /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o55+ww6522_ber_rVipBer3_aln_9.83417.bam o55 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7/chr_7_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_7




###chr_8-17

vim commands_chr8-17.txt


bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2cn+S3-SVb091_ber_rVipBer3_7.20274.bam 2cn /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/nu0+S6-SVb163_ber_rVipBer3_21.14275.bam nu0 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2rd+S8-SVb229_ber_rVipBer3_17.84131.bam 2rd /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/d79+S9-SVb230_ber_rVipBer3_14.86320.bam d79 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/6i5+S10-SVb271_ber_rVipBer3_13.22348.bam 6i5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x1t+S11-SVb316_ber_rVipBer3_9.10306.bam x1t /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o8g+S12-SVb371_ber_rVipBer3_32.21524.bam o8g /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/2sj+S13-SVb399_ber_rVipBer3_14.67941.bam 2sj /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/42r+S14-SVb410_ber_rVipBer3_21.13850.bam 42r /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/46y+S22_1895_ber_rVipBer3_7.58190.bam 46y /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/h9d+S24_1895_ber_rVipBer3_7.70202.bam h9d /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/rzt+S26_1895_ber_rVipBer3_9.42227.bam rzt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/hpa+S28_1908_ber_rVipBer3_16.86980.bam hpa /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5h5+S29_1894_ber_rVipBer3_12.72974.bam 5h5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/vyo+S30_1894_ber_rVipBer3_13.62265.bam vyo /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4w7+S31_1917_ber_rVipBer3_27.24751.bam 4w7 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/5fu+S32_1917_ber_rVipBer3_29.72487.bam 5fu /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/me5+S33_1917_ber_rVipBer3_24.70592.bam me5 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/mnw+S34_1896_ber_rVipBer3_9.99212.bam mnw /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/gvw+S35_1896_ber_rVipBer3_15.11601.bam gvw /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/ivx_th6+ww6523_ber_rVipBer3_aln_9.39783.bam ivx /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o5k_bo6+ww6524_ber_rVipBer3_aln_9.25411.bam o5k /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/4rs+ww6514_ber_rVipBer3_aln_21.72646.bam 4rs /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/eyL_xaw+ww6515_ber_rVipBer3_aln_9.40289.bam eyL /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/x3v_a31+ww6516_ber_rVipBer3_aln_8.82775.bam x3v /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/qdL_c8p+ww6518_ber_rVipBer3_aln_9.40188.bam qdL /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/whu_wd3+ww6519_ber_rVipBer3_aln_9.09410.bam whu /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
bash loopangsd_het_chr2.sh /scratch/SCWF00035/BEARCAVE0/mappedrVipBer3_aln/o55+ww6522_ber_rVipBer3_aln_9.83417.bam o55 /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17/chr_8-17_50kb_windows.txt /scratch/SCWF00035/people/b.dvb25fyc_david/BEARCAVE2/het_rmtrans/chr_8-17
```

# plotting of heterozygosity and runs of homozygosity graphs in R

```{r, echo=FALSE, eval=TRUE}
setwd("C:/Users/dange/het_working_directory")

library(dplyr)
library(kableExtra)



## 2cn ##

icn_depth <- read.table("2cn.window.depth")
colnames(icn_depth)[1] <- "window"

icn_het <- read.table("2cn_all.window.sfs", fill=TRUE)
colnames(icn_het)[1] <- "window"

##compute mean depth per window

icn_means <- apply(icn_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = icn_depth$window,
  depth = icn_means
)

##computing het

icn_het <- icn_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, icn_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


##nu0 plot


##reading both files with and explicit window column
## not relying on row names

nu0_depth <- read.table("nu0.window.depth")
colnames(nu0_depth)[1] <- "window"

nu0_het <- read.table("nu0_all.window.sfs", fill=TRUE)
colnames(nu0_het)[1] <- "window"

##compute mean depth per window

nu0_means <- apply(nu0_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = nu0_depth$window,
  depth = nu0_means
)

##computing het

nu0_het <- nu0_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, nu0_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


##2rd plot


##reading both files with and explicit window column
## not relying on row names

erd_depth <- read.table("2rd.window.depth")
colnames(erd_depth)[1] <- "window"

erd_het <- read.table("2rd_all.window.sfs", fill=TRUE)
colnames(erd_het)[1] <- "window"

##compute mean depth per window

erd_means <- apply(erd_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = erd_depth$window,
  depth = erd_means
)

##computing het

erd_het <- erd_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, erd_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


##d79 plot


##reading both files with and explicit window column
## not relying on row names

d79_depth <- read.table("d79.window.depth")
colnames(d79_depth)[1] <- "window"

d79_het <- read.table("d79_all.window.sfs", fill=TRUE)
colnames(d79_het)[1] <- "window"

##compute mean depth per window

d79_means <- apply(d79_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = d79_depth$window,
  depth = d79_means
)

##computing het

d79_het <- d79_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, d79_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


##6i5 plot


##reading both files with and explicit window column
## not relying on row names

hi5_depth <- read.table("6i5.window.depth")
colnames(hi5_depth)[1] <- "window"

hi5_het <- read.table("6i5_all.window.sfs", fill=TRUE)
colnames(hi5_het)[1] <- "window"

##compute mean depth per window

hi5_means <- apply(hi5_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = hi5_depth$window,
  depth = hi5_means
)

##computing het

hi5_het <- hi5_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, hi5_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


##x1t plot


##reading both files with and explicit window column
## not relying on row names

x1t_depth <- read.table("x1t.window.depth")
colnames(x1t_depth)[1] <- "window"

x1t_het <- read.table("x1t_all.window.sfs", fill=TRUE)
colnames(x1t_het)[1] <- "window"

##compute mean depth per window

x1t_means <- apply(x1t_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = x1t_depth$window,
  depth = x1t_means
)

##computing het

x1t_het <- x1t_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, x1t_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


##o8g plot


##reading both files with and explicit window column
## not relying on row names

o8g_depth <- read.table("o8g.window.depth")
colnames(o8g_depth)[1] <- "window"

o8g_het <- read.table("o8g_all.window.sfs", fill=TRUE)
colnames(o8g_het)[1] <- "window"

##compute mean depth per window

o8g_means <- apply(o8g_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = o8g_depth$window,
  depth = o8g_means
)

##computing het

o8g_het <- o8g_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, o8g_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


##2sj plot


##reading both files with and explicit window column
## not relying on row names

fsj_depth <- read.table("2sj.window.depth")
colnames(fsj_depth)[1] <- "window"

fsj_het <- read.table("2sj_all.window.sfs", fill=TRUE)
colnames(fsj_het)[1] <- "window"

##compute mean depth per window

fsj_means <- apply(fsj_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = fsj_depth$window,
  depth = fsj_means
)

##computing het

fsj_het <- fsj_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, fsj_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


##42r plot


##reading both files with and explicit window column
## not relying on row names

g2r_depth <- read.table("42r.window.depth")
colnames(g2r_depth)[1] <- "window"

g2r_het <- read.table("42r_all.window.sfs", fill=TRUE)
colnames(g2r_het)[1] <- "window"

##compute mean depth per window

g2r_means <- apply(g2r_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = g2r_depth$window,
  depth = g2r_means
)

##computing het

g2r_het <- g2r_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, g2r_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


##46y plot


##reading both files with and explicit window column
## not relying on row names

a6y_depth <- read.table("46y.window.depth")
colnames(a6y_depth)[1] <- "window"

a6y_het <- read.table("46y_all.window.sfs", fill=TRUE)
colnames(a6y_het)[1] <- "window"

##compute mean depth per window

a6y_means <- apply(a6y_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = a6y_depth$window,
  depth = a6y_means
)

##computing het

a6y_het <- a6y_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, a6y_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


##h9d plot


##reading both files with and explicit window column
## not relying on row names

h9d_depth <- read.table("h9d.window.depth")
colnames(h9d_depth)[1] <- "window"

h9d_het <- read.table("h9d_all.window.sfs", fill=TRUE)
colnames(h9d_het)[1] <- "window"

##compute mean depth per window

h9d_means <- apply(h9d_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = h9d_depth$window,
  depth = h9d_means
)

##computing het

h9d_het <- h9d_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, h9d_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


##rzt plot


##reading both files with and explicit window column
## not relying on row names

rzt_depth <- read.table("rzt.window.depth")
colnames(rzt_depth)[1] <- "window"

rzt_het <- read.table("rzt_all.window.sfs", fill=TRUE)
colnames(rzt_het)[1] <- "window"

##compute mean depth per window

rzt_means <- apply(rzt_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = rzt_depth$window,
  depth = rzt_means
)

##computing het

rzt_het <- rzt_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, rzt_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)



##hpa plot


##reading both files with and explicit window column
## not relying on row names

hpa_depth <- read.table("hpa.window.depth")
colnames(hpa_depth)[1] <- "window"

hpa_het <- read.table("hpa_all.window.sfs", fill=TRUE)
colnames(hpa_het)[1] <- "window"

##compute mean depth per window

hpa_means <- apply(hpa_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = hpa_depth$window,
  depth = hpa_means
)

##computing het

hpa_het <- hpa_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, hpa_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


##5h5 plot


##reading both files with and explicit window column
## not relying on row names

bh5_depth <- read.table("5h5.window.depth")
colnames(bh5_depth)[1] <- "window"

bh5_het <- read.table("5h5_all.window.sfs", fill=TRUE)
colnames(bh5_het)[1] <- "window"

##compute mean depth per window

bh5_means <- apply(bh5_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = bh5_depth$window,
  depth = bh5_means
)

##computing het

bh5_het <- bh5_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, bh5_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


##vyo plot


##reading both files with and explicit window column
## not relying on row names

vyo_depth <- read.table("vyo.window.depth")
colnames(vyo_depth)[1] <- "window"

vyo_het <- read.table("vyo_all.window.sfs", fill=TRUE)
colnames(vyo_het)[1] <- "window"

##compute mean depth per window

vyo_means <- apply(vyo_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = vyo_depth$window,
  depth = vyo_means
)

##computing het

vyo_het <- vyo_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, vyo_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


##4w7 plot


##reading both files with and explicit window column
## not relying on row names

cw7_depth <- read.table("4w7.window.depth")
colnames(cw7_depth)[1] <- "window"

cw7_het <- read.table("4w7_all.window.sfs", fill=TRUE)
colnames(cw7_het)[1] <- "window"

##compute mean depth per window

cw7_means <- apply(cw7_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = cw7_depth$window,
  depth = cw7_means
)

##computing het

cw7_het <- cw7_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, cw7_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)



##5fu plot


##reading both files with and explicit window column
## not relying on row names

dfu_depth <- read.table("5fu.window.depth")
colnames(dfu_depth)[1] <- "window"

dfu_het <- read.table("5fu_all.window.sfs", fill=TRUE)
colnames(dfu_het)[1] <- "window"

##compute mean depth per window

dfu_means <- apply(dfu_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = dfu_depth$window,
  depth = dfu_means
)

##computing het

dfu_het <- dfu_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, dfu_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)



##me5 plot


##reading both files with and explicit window column
## not relying on row names

me5_depth <- read.table("me5.window.depth")
colnames(me5_depth)[1] <- "window"

me5_het <- read.table("me5_all.window.sfs", fill=TRUE)
colnames(me5_het)[1] <- "window"

##compute mean depth per window

me5_means <- apply(me5_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = me5_depth$window,
  depth = me5_means
)

##computing het

me5_het <- me5_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, me5_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


##mnw plot


##reading both files with and explicit window column
## not relying on row names

mnw_depth <- read.table("mnw.window.depth")
colnames(mnw_depth)[1] <- "window"

mnw_het <- read.table("mnw_all.window.sfs", fill=TRUE)
colnames(mnw_het)[1] <- "window"

##compute mean depth per window

mnw_means <- apply(mnw_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = mnw_depth$window,
  depth = mnw_means
)

##computing het

mnw_het <- mnw_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, mnw_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)



##gvw plot


##reading both files with and explicit window column
## not relying on row names

gvw_depth <- read.table("gvw.window.depth")
colnames(gvw_depth)[1] <- "window"

gvw_het <- read.table("gvw_all.window.sfs", fill=TRUE)
colnames(gvw_het)[1] <- "window"

##compute mean depth per window

gvw_means <- apply(gvw_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = gvw_depth$window,
  depth = gvw_means
)

##computing het

gvw_het <- gvw_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, gvw_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16) 




## ivx

ivx_depth <- read.table("ivx.window.depth")
colnames(ivx_depth)[1] <- "window"

ivx_het <- read.table("ivx_all.window.sfs", fill=TRUE)
colnames(ivx_het)[1] <- "window"

##compute mean depth per window

ivx_means <- apply(ivx_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = ivx_depth$window,
  depth = ivx_means
)

##computing het

ivx_het <- ivx_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, ivx_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)
     
    
## o5k    

o5k_depth <- read.table("o5k.window.depth")
colnames(o5k_depth)[1] <- "window"

o5k_het <- read.table("o5k_all.window.sfs", fill=TRUE)
colnames(o5k_het)[1] <- "window"

##compute mean depth per window

o5k_means <- apply(o5k_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = o5k_depth$window,
  depth = o5k_means
)

##computing het

o5k_het <- o5k_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, o5k_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)



## 4rs

irs_depth <- read.table("4rs.window.depth")
colnames(irs_depth)[1] <- "window"

irs_het <- read.table("4rs_all.window.sfs", fill=TRUE)
colnames(irs_het)[1] <- "window"

##compute mean depth per window

irs_means <- apply(irs_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = irs_depth$window,
  depth = irs_means
)

##computing het

irs_het <- irs_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, irs_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


## eyL


eyL_depth <- read.table("eyL.window.depth")
colnames(eyL_depth)[1] <- "window"

eyL_het <- read.table("eyL_all.window.sfs", fill=TRUE)
colnames(eyL_het)[1] <- "window"

##compute mean depth per window

eyL_means <- apply(eyL_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = eyL_depth$window,
  depth = eyL_means
)

##computing het

eyL_het <- eyL_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, eyL_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


## x3v


x3v_depth <- read.table("x3v.window.depth")
colnames(x3v_depth)[1] <- "window"

x3v_het <- read.table("x3v_all.window.sfs", fill=TRUE)
colnames(x3v_het)[1] <- "window"

##compute mean depth per window

x3v_means <- apply(x3v_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = x3v_depth$window,
  depth = x3v_means
)

##computing het

x3v_het <- x3v_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, x3v_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)



## qdl


qdl_depth <- read.table("qdl.window.depth")
colnames(qdl_depth)[1] <- "window"

qdl_het <- read.table("qdl_all.window.sfs", fill=TRUE)
colnames(qdl_het)[1] <- "window"

##compute mean depth per window

qdl_means <- apply(qdl_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = qdl_depth$window,
  depth = qdl_means
)

##computing het

qdl_het <- qdl_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, qdl_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


## whu


whu_depth <- read.table("whu.window.depth")
colnames(whu_depth)[1] <- "window"

whu_het <- read.table("whu_all.window.sfs", fill=TRUE)
colnames(whu_het)[1] <- "window"

##compute mean depth per window

whu_means <- apply(whu_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = whu_depth$window,
  depth = whu_means
)

##computing het

whu_het <- whu_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, whu_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)


## o55


o55_depth <- read.table("o55.window.depth")
colnames(o55_depth)[1] <- "window"

o55_het <- read.table("o55_all.window.sfs", fill=TRUE)
colnames(o55_het)[1] <- "window"

##compute mean depth per window

o55_means <- apply(o55_depth[,-1], 1, function(counts) {
  values <- seq(0, length(counts) - 1)
  weighted.mean(values, counts)
})

depth_df <- data.frame(
  window = o55_depth$window,
  depth = o55_means
)

##computing het

o55_het <- o55_het %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

##merging by window so the data matches up and can be plotted

df <- merge(depth_df, o55_het, by = "window")

plot(df$depth, df$het,
     xlab = "Mean depth",
     ylab = "Heterozygosity",
     pch = 16)



# manhattan plots used in final results ##################



### o8g ####


o8g <- read.table(
  "chr_1/o8g.window.sfs",
  fill = TRUE
) %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

# Extract midpoint of each window and convert to Mb
o8g_pos <- sapply(
  strsplit(sub(".*:", "", o8g[[1]]), "-"),
  function(x) mean(as.numeric(x))
) / 1e6

# Heterozygosity per kb
o8g_het <- o8g$het * 1000


# ------------------------------------------------------------
# Figure parameters
# ------------------------------------------------------------


par(
  mar = c(5, 5, 4, 7),   # large right margin
  bty = "l",
  las = 1
)


# ------------------------------------------------------------
# Main plot
# ------------------------------------------------------------

plot(
  o8g_pos,
  o8g_het,
  type = "p",
  pch = 16,
  cex = 0.45,
  col = ifelse(
    o8g_het > 0.2,
    "#2166AC",
    "#D73027"
  ),
  
  ylim = c(0, 5),
  yaxs = "i",
  
  xaxt = "n",
  xlab = "Position in chr_1 (Mb)",
  ylab = "het/kb",
  main = "o8g-S12-SVb371 mod other",
  
  cex.axis = 1.1,
  cex.lab = 1.2,
  cex.main = 1.25
)


# ------------------------------------------------------------
# Add grid lines ONLY inside plotting region
# ------------------------------------------------------------

# Save current clipping region
usr <- par("usr")

# Restrict drawing to plot region
clip(
  usr[1],
  usr[2],
  usr[3],
  usr[4]
)

abline(
  h = seq(0, 5, by = 1),
  col = "#E6E6E6",
  lty = 1,
  lwd = 1
)


# ------------------------------------------------------------
# Redraw points over grid
# ------------------------------------------------------------

points(
  o8g_pos,
  o8g_het,
  pch = 16,
  cex = 0.45,
  col = ifelse(
    o8g_het > 0.2,
    "#2166AC",
    "#D73027"
  )
)


# ------------------------------------------------------------
# X-axis
# ------------------------------------------------------------

x_max <- ceiling(max(o8g_pos, na.rm = TRUE))

axis(
  1,
  at = seq(0, x_max, by = 10),
  labels = seq(0, x_max, by = 10),
  cex.axis = 1.1
)


# ------------------------------------------------------------
# Legend OUTSIDE plotting region
# ------------------------------------------------------------

par(xpd = NA)

legend(
  "topright",
  inset = c(-0.43, 0),
  legend = c(
    "het > 0.2",
    "het ≤ 0.2"
  ),
  col = c(
    "#2166AC",
    "#D73027"
  ),
  x.intersp = 0.1,
  y.intersp = 0.5,
  pch = 16,
  pt.cex = 0.9,
  bty = "n",
  cex = 0.9
)

# Reset clipping
par(xpd = FALSE)



### o5k ###


o5k <- read.table(
  "chr_1/o5k.window.sfs",
  fill = TRUE
) %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

# Extract midpoint of each window and convert to Mb
o5k_pos <- sapply(
  strsplit(sub(".*:", "", o5k[[1]]), "-"),
  function(x) mean(as.numeric(x))
) / 1e6

# Heterozygosity per kb
o5k_het <- o5k$het * 1000


# ------------------------------------------------------------
# Figure parameters
# ------------------------------------------------------------


par(
  mar = c(5, 5, 4, 7),   # large right margin
  bty = "l",
  las = 1
)


# ------------------------------------------------------------
# Main plot
# ------------------------------------------------------------

plot(
  o5k_pos,
  o5k_het,
  type = "p",
  pch = 16,
  cex = 0.45,
  col = ifelse(
    o5k_het > 0.2,
    "#2166AC",
    "#D73027"
  ),
  
  ylim = c(0, 5),
  yaxs = "i",
  
  xaxt = "n",
  xlab = "Position in chr_1 (Mb)",
  ylab = "het/kb",
  main = "o5k_bo6-ww6524 mod Lyndhurst",
  
  cex.axis = 1.1,
  cex.lab = 1.2,
  cex.main = 1.25
)


# ------------------------------------------------------------
# Add grid lines ONLY inside plotting region
# ------------------------------------------------------------

# Save current clipping region
usr <- par("usr")

# Restrict drawing to plot region
clip(
  usr[1],
  usr[2],
  usr[3],
  usr[4]
)

abline(
  h = seq(0, 5, by = 1),
  col = "#E6E6E6",
  lty = 1,
  lwd = 1
)


# ------------------------------------------------------------
# Redraw points over grid
# ------------------------------------------------------------

points(
  o5k_pos,
  o5k_het,
  pch = 16,
  cex = 0.45,
  col = ifelse(
    o5k_het > 0.2,
    "#2166AC",
    "#D73027"
  )
)


# ------------------------------------------------------------
# X-axis
# ------------------------------------------------------------

x_max <- ceiling(max(o5k_pos, na.rm = TRUE))

axis(
  1,
  at = seq(0, x_max, by = 10),
  labels = seq(0, x_max, by = 10),
  cex.axis = 1.1
)


# ------------------------------------------------------------
# Legend OUTSIDE plotting region
# ------------------------------------------------------------

par(xpd = NA)

legend(
  "topright",
  inset = c(-0.43, 0),
  legend = c(
    "het > 0.2",
    "het ≤ 0.2"
  ),
  col = c(
    "#2166AC",
    "#D73027"
  ),
  x.intersp = 0.1,
  y.intersp = 0.5,
  pch = 16,
  pt.cex = 0.9,
  bty = "n",
  cex = 0.9
)

# Reset clipping
par(xpd = FALSE)






### 5fu ###

dfu <- read.table(
  "chr_1/5fu.window.sfs",
  fill = TRUE
) %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

# Extract midpoint of each window and convert to Mb
dfu_pos <- sapply(
  strsplit(sub(".*:", "", dfu[[1]]), "-"),
  function(x) mean(as.numeric(x))
) / 1e6

# Heterozygosity per kb
dfu_het <- dfu$het * 1000


# ------------------------------------------------------------
# Figure parameters
# ------------------------------------------------------------


par(
  mar = c(5, 5, 4, 7),   # large right margin
  bty = "l",
  las = 1
)


# ------------------------------------------------------------
# Main plot
# ------------------------------------------------------------

plot(
  dfu_pos,
  dfu_het,
  type = "p",
  pch = 16,
  cex = 0.45,
  col = ifelse(
    dfu_het > 0.2,
    "#2166AC",
    "#D73027"
  ),
  
  ylim = c(0, 5),
  yaxs = "i",
  
  xaxt = "n",
  xlab = "Position in chr_1 (Mb)",
  ylab = "het/kb",
  main = "5fu-S32_1917 hist Brockenhurst",
  
  cex.axis = 1.1,
  cex.lab = 1.2,
  cex.main = 1.25
)


# ------------------------------------------------------------
# Add grid lines ONLY inside plotting region
# ------------------------------------------------------------

# Save current clipping region
usr <- par("usr")

# Restrict drawing to plot region
clip(
  usr[1],
  usr[2],
  usr[3],
  usr[4]
)

abline(
  h = seq(0, 5, by = 1),
  col = "#E6E6E6",
  lty = 1,
  lwd = 1
)


# ------------------------------------------------------------
# Redraw points over grid
# ------------------------------------------------------------

points(
  dfu_pos,
  dfu_het,
  pch = 16,
  cex = 0.45,
  col = ifelse(
    dfu_het > 0.2,
    "#2166AC",
    "#D73027"
  )
)


# ------------------------------------------------------------
# X-axis
# ------------------------------------------------------------

x_max <- ceiling(max(dfu_pos, na.rm = TRUE))

axis(
  1,
  at = seq(0, x_max, by = 10),
  labels = seq(0, x_max, by = 10),
  cex.axis = 1.1
)


# ------------------------------------------------------------
# Legend OUTSIDE plotting region
# ------------------------------------------------------------

par(xpd = NA)

legend(
  "topright",
  inset = c(-0.43, 0),
  legend = c(
    "het > 0.2",
    "het ≤ 0.2"
  ),
  col = c(
    "#2166AC",
    "#D73027"
  ),
  x.intersp = 0.1,
  y.intersp = 0.5,
  pch = 16,
  pt.cex = 0.9,
  bty = "n",
  cex = 0.9
)

# Reset clipping
par(xpd = FALSE)




### rzt ###
# marginally different code as the clipping function was clashing with the par function
# x axis and figure legend were being removed 

rzt <- read.table(
  "chr_1/rzt.window.sfs",
  fill = TRUE
) %>%
  mutate(
    sum = V2 + V3 + V4,
    het = V3 / sum
  )

# Extract midpoint of each window and convert to Mb
rzt_pos <- sapply(
  strsplit(sub(".*:", "", rzt[[1]]), "-"),
  function(x) mean(as.numeric(x))
) / 1e6

# Heterozygosity per kb
rzt_het <- rzt$het * 1000


# ------------------------------------------------------------
# Figure parameters
# ------------------------------------------------------------

par(
  mar = c(5, 5, 4, 7),
  bty = "l",
  las = 1,
  xpd = FALSE
)


# ------------------------------------------------------------
# Main plot
# ------------------------------------------------------------

plot(
  rzt_pos,
  rzt_het,
  type = "p",
  pch = 16,
  cex = 0.45,
  col = ifelse(
    rzt_het > 0.2,
    "#2166AC",
    "#D73027"
  ),
  
  ylim = c(0, 5),
  yaxs = "i",
  
  xaxt = "n",
  xlab = "Position in chr_1 (Mb)",
  ylab = "het/kb",
  main = "rzt-S26_1895 hist Lyndhurst",
  
  cex.axis = 1.1,
  cex.lab = 1.2,
  cex.main = 1.25
)


# ------------------------------------------------------------
# Add grid lines ONLY inside plotting region
# ------------------------------------------------------------

usr <- par("usr")

segments(
  x0 = usr[1],
  y0 = seq(0, 5, by = 1),
  x1 = usr[2],
  y1 = seq(0, 5, by = 1),
  col = "#E6E6E6",
  lty = 1,
  lwd = 1
)


# ------------------------------------------------------------
# Redraw points over grid
# ------------------------------------------------------------

points(
  rzt_pos,
  rzt_het,
  pch = 16,
  cex = 0.45,
  col = ifelse(
    rzt_het > 0.2,
    "#2166AC",
    "#D73027"
  )
)


# ------------------------------------------------------------
# X-axis
# ------------------------------------------------------------

x_max <- ceiling(max(rzt_pos, na.rm = TRUE))

axis(
  1,
  at = seq(0, x_max, by = 10),
  labels = seq(0, x_max, by = 10),
  cex.axis = 1.1
)


# ------------------------------------------------------------
# Legend OUTSIDE plotting region
# ------------------------------------------------------------

par(xpd = NA)

legend(
  "topright",
  inset = c(-0.43, 0),
  legend = c(
    "het > 0.2",
    "het ≤ 0.2"
  ),
  col = c(
    "#2166AC",
    "#D73027"
  ),
  x.intersp = 0.1,
  y.intersp = 0.5,
  pch = 16,
  pt.cex = 0.9,
  bty = "n",
  cex = 0.9
)

# Reset clipping
par(xpd = FALSE)


## genetic health ##


##defining variables

##define the individuals
## when adding samples the read in list dictates the order of the variables and it changes
sample_names <- c("2cn", "2rd", "2sj", "42r", "46y", "4rs", "4w7", "5fu", "5h5", "6i5", "d79", "eyL", "gvw", "h9d", "hpa", "ivx", "me5", "mnw", "nu0", "o55", "o5k", "o8g", "qdl", "rzt", "vyo", "whu", "x1t", "x3v")

# define the individuals again (makes graphs easier to interpret?)
pop <- c("2cn", "2rd", "2sj", "42r", "46y", "4rs", "4w7", "5fu", "5h5", "6i5", "d79", "eyL", "gvw", "h9d", "hpa", "ivx", "me5", "mnw", "nu0", "o55", "o5k", "o8g", "qdl", "rzt", "vyo", "whu", "x1t", "x3v")

# define country of origin
country_pop <- c("UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK", "UK")

# define colour vector 
colour_pop <- c("#999999", "#999999", "#999999", "#999999", "black", "#556B2F", "#E7298A", "#E7298A", "#E7298A", "#999999", "#556B2F", "#556B2F", "#E7298A", "black", "#E7298A", "#556B2F", "#E7298A", "#E7298A", "#999999", "#556B2F", "#556B2F", "#999999", "#556B2F", "#E7298A", "#E7298A", "#556B2F", "#999999",  "#556B2F")    

# define shapes vector 

shape_pop <- c(
  "#999999" = 1,
  "#E7298A" = 0,
  "#556B2F" = 2,
  "black" = 0
)[colour_pop]


# Then we read in and assigned our sfs estimates to a variable


for (sample in sample_names){
  # construct the file name
  file_name <- paste0(sample, "_all.window.sfs")
  
  # read in whole genome sfs file
  whole_genome <- read.table(file_name, fill = TRUE)
  
  # assign whole genome sfs to a variable
  assign(paste0(sample, "_whole_genome"), whole_genome)
}

remove(sample)
remove(file_name)
remove(whole_genome)





##heterozygosity workthrough


# function to calculate window size

calculate_window_size <- function(window) {
  positions <- strsplit(window, "[:-]")[[1]]
  start <- as.numeric(positions[2])
  end <- as.numeric(positions[3])
  return(end - start + 1)
}

# create a list of all whole genomes
whole_genome_list <- ls(pattern = "whole_genome")

# loop over each samples
for (genome_name in whole_genome_list){
  # read in whole genome variable
  genome <- get(genome_name)
  
  # add new column for window size
  genome$window_size <- sapply(genome$V1, calculate_window_size)
  
  # filter out rows with  window size < 50kb
  genome <- genome %>% dplyr::filter(window_size >= 50000)
  
  # filter out rows with NA values
  genome <- genome %>% dplyr::filter(!is.na(V3))
  
  # assign the filtered genome back to the environment
  assign(genome_name, genome)
}

# remove loop variables
remove(genome_name)
remove(genome)


#Now we can calculate the heterozygosity for each individual. 

# create empty vector to store het values
het_kb_vector <- c()

# create vector to store name of samples 
sample_name_vector <- c()

# loop over each samples
for (sample_name_het in whole_genome_list){
  # read in whole genome variable
  genome <- get(sample_name_het)
  
  # calculate het per kb
  genome_het <- transmute(genome, het = (V3/(V2 + V3 + V4)) * 1000)
  
  # calculate average 
  mean_het <- mean(genome_het$het)
  
  # keep only sample (rename)
  sample_name_cleaned <- gsub("_whole_genome", "", sample_name_het)
  
  # store het per kb in vector
  het_kb_vector <- c(het_kb_vector, mean_het)
  
  # store sample name in vector 
  sample_name_vector <- c(sample_name_vector, sample_name_cleaned)
}

# remove loop variables
remove(sample_name_het)
remove(sample_name_cleaned)
remove(mean_het)
remove(genome)
remove(genome_het)



# create dataframe for het kb per pos
het_kb_df <- data.frame(sample = sample_name_vector, 
                        het = het_kb_vector)

#Now plot the heterozygosity for each individual. 

# add a column to dataframe with het per kb values with the population of each sample
het_kb_df$pop <- NA

# add population to dataframe
het_kb_df$pop <- pop

# add a column to dataframe with het per kb values with the country of each sample
het_kb_df$country <- NA

# add population to dataframe
het_kb_df$country <- country_pop

# add colours column 
het_kb_df$colour <- colour_pop

# arrange by colour first (as this corresponds with nhm or modern day) then by population
het_kb_df <- het_kb_df[order(het_kb_df$colour, het_kb_df$pop), ]

# creating boxplot dataframes for mean het
# this creates 3 seperate dataframes for
# modern brockenhurst and Lynhurst pop
# historic brockenhurst and Lyndhurst pop
# modern all other locations
# over complicated because didn't want to remove DNA damaged samples but then removed anyway
# so not repeated for ROH boxplot


df_mod_brocklynd <- het_kb_df[het_kb_df$colour == "#556B2F", ]

df_mod_other <- het_kb_df[het_kb_df$colour == "#999999", ]

df_hist_brocklynd <- het_kb_df[het_kb_df$colour %in% c("#E7298A", "black"),]



# boxplots with points overlayed for accuracy

library(ggplot2)
# creates a group column with the corresponding colours

df_mod_brocklynd$group <- "#556B2F"
df_mod_other$group <- "#999999"
df_hist_brocklynd$group <- "#E7298A"


# binds all the dataframe into one dataframe called plot_df

plot_df$group <- ifelse(
  plot_df$colour == "#556B2F",
  "Modern_Brock_Lynd",
  ifelse(
    plot_df$colour == "#999999",
    "Modern_other",
    ifelse(
      plot_df$colour %in% c("#E7298A", "black"),
      "Historic_Brock_Lynd",
      NA
    )
  )
)

plot_df$group <- factor(
  plot_df$group,
  levels = c(
    "Modern_Brock_Lynd",
    "Modern_other",
    "Historic_Brock_Lynd"
  )
)

# remove samples associated with colour black as they are too DNA damaged to use

plot_df <- plot_df %>%
  filter(colour != "black")


# boxplot of mean het per group with  #
# the lower/upper whisker is 1.5 × IQR of Q1/Q3.

# Set group order
mean_roh_length_df$group <- factor(
  mean_roh_length_df$group,
  levels = c(
    "Modern_Brock_Lynd",
    "Modern_other",
    "Historic_Brock_Lynd"
  )
)

# Boxplot of mean ROH length per group
# Lower/upper whisker is 1.5 × IQR of Q1/Q3

library(ggplot2)

ggplot(mean_roh_length_df, aes(x = group, y = mean_roh_length)) +
  
  geom_boxplot(
    aes(fill = colour),
    colour = "black",
    width = 0.55,
    linewidth = 0.9,
    alpha = 0.20,
    outlier.shape = NA,
    coef = 1.5
  ) +
  
  stat_boxplot(
    geom = "errorbar",
    colour = "black",
    width = 0.20,
    linewidth = 0.9
  ) +
  
  geom_jitter(
    aes(colour = colour),
    width = 0.10,
    size = 2.7,
    alpha = 0.85
  ) +
  
  scale_colour_identity() +
  scale_fill_identity() +
  
  labs(
    x = "Group",
    y = "Mean ROH length",
    title = "mean_roh_length for all samples excluding DNA damaged hist"
  ) +
  
  theme_classic(base_size = 14) +
  
  theme(
    plot.title = element_text(
      size = 14,
      face = "bold",
      hjust = 0.5
    ),
    axis.title = element_text(size = 15),
    axis.text = element_text(size = 12, colour = "black"),
    axis.line = element_line(linewidth = 0.8),
    axis.ticks = element_line(linewidth = 0.7)
  )




# boxplot of mean het per group with  #
# the lower/upper whisker is min and max in each group


# Set group order
mean_roh_length_df$group <- factor(
  mean_roh_length_df$group,
  levels = c(
    "Modern_Brock_Lynd",
    "Modern_other",
    "Historic_Brock_Lynd"
  )
)

library(ggplot2)

ggplot(mean_roh_length_df, aes(x = group, y = mean_roh_length)) +
  
  # Boxplots
  geom_boxplot(
    aes(fill = colour),
    colour = "black",
    width = 0.55,
    linewidth = 0.9,
    alpha = 0.20,
    outlier.shape = NA
  ) +
  
  # Whiskers extending to minimum and maximum
  stat_summary(
    fun.min = min,
    fun.max = max,
    geom = "errorbar",
    colour = "black",
    width = 0.20,
    linewidth = 0.9
  ) +
  
  # Individual samples
  geom_jitter(
    aes(colour = colour),
    width = 0.10,
    height = 0,
    size = 2.7,
    alpha = 0.85
  ) +
  
  # Use colours specified in dataframe
  scale_colour_identity() +
  scale_fill_identity() +
  
  labs(
    x = "Group",
    y = "Mean ROH length",
    title = "mean_roh_length for all samples excluding DNA damaged hist"
  ) +
  
  theme_classic(base_size = 14) +
  
  theme(
    plot.title = element_text(
      size = 14,
      face = "bold",
      hjust = 0.5
    ),
    axis.title = element_text(size = 15),
    axis.text = element_text(size = 12, colour = "black"),
    axis.line = element_line(linewidth = 0.8),
    axis.ticks = element_line(linewidth = 0.7)
  )





## ROH and FROH ##


#Runs of Homozygosity (ROH) are defined as long stretches of homozygous genotypes. 
#We calculated ROHs by looking at the number of heterozygous positions in each window, 
#and using a threshold of 10 heterozygous to define a potential ROH.

#1. `analROH` - this function calculate the length of ROHs in a sample based on 
#a give threshold.

#2. `countROH` - this function counts the number of ROHs in a sample based on their length

library(stringr)


#Now we can calculate the ROHs for each individual!

# setting up the functions

analROH <- function(input_data, threshold = 1000) {
  result <- input_data %>%
    filter(V3 < threshold) %>% 
    mutate(adj_count = cumsum(c(0, diff(position) != 1))) %>%
    group_by(adj_count) %>%
    summarise(adj_count = n(),
              start_row = first(position),
              end_row = last(position)) %>%
    mutate(ROH_Length_KB = adj_count * 50000) %>% # check used window size
    mutate(ROH_Length_MB = ROH_Length_KB / 1000000) %>% 
    filter(ROH_Length_MB >= 0.1) %>% # keep only ROHs >= 100kb
    select(adj_count, ROH_Length_KB, ROH_Length_MB, start_row, end_row)
  
  return(result)
}

countROH <- function(input_data, ROH_Length_MB) {
  result <- input_data %>%
    group_by({{ ROH_Length_MB }}) %>%
    summarise(count = n())
  
  return(result)
}

#calculating for each individual 

for (genome_name in whole_genome_list){
  # read in whole genome variable
  genome <- get(genome_name)
  
  # add a column with row index
  genome <- cbind(genome, "position" = 1:nrow(genome))
  
  # update original whole genome object
  assign(genome_name, genome, envir = .GlobalEnv)
  
  # remove "_whole_genome" from ROHOUT_name (rename variable)
  genome_name <- gsub("_whole_genome", "", genome_name)
  
  # assign variable name for length output
  ROHOUT_name <- paste(genome_name, "ROHOUT", sep = "_")
  
  # calculate ROH length
  assign(ROHOUT_name, analROH(genome, threshold = 10))
  
  # assign variable name for count output
  ROHCOUNT_name <- paste(genome_name, "ROHCOUNT", sep = "_")
  
  # calculate ROH count
  assign(ROHCOUNT_name, countROH(get(ROHOUT_name), ROH_Length_MB))
  
}

# remove loop variables
remove(genome_name)
remove(genome)
remove(ROHOUT_name)
remove(ROHCOUNT_name)


# Calculate mean length of ROH

# list of all the samples
ROHOUT_list <- ls(pattern = "ROHOUT")

# create empty vector to store mean length values
mean_length_vector <- c()

# loop through all ROHOUT samples
for (ROHOUT_name in ROHOUT_list) {
  # get rohout file
  rohout <- get(ROHOUT_name)
  
  # calculate mean length ROH
  rohout_mean <- rohout %>%
    summarise(mean_ROH_length = mean(ROH_Length_MB))
  
  # store mean length values
  mean_length_vector <- c(mean_length_vector, rohout_mean$mean_ROH_length)
  
}

# remove loop variables
remove(ROHOUT_name)
remove(rohout)
remove(rohout_mean)

# reorder ROHOUT_list to match sample names
ROHOUT_list <- ROHOUT_list[match(sample_names, str_remove(ROHOUT_list, "_ROHOUT"))]

# create dataframe for mean length 
mean_roh_length_df <- data.frame(sample = sample_names,
                                 mean_roh_length = mean_length_vector)


# plotting mean ROH for each individual 

# add a column to dataframe with mean_roh_length per kb values with the population of each sample
mean_roh_length_df$pop <- NA

# add population to dataframe
mean_roh_length_df$pop <- pop

# add a column to dataframe with mean_roh_length per kb values with the country of each sample
mean_roh_length_df$country <- NA

# add population to dataframe
mean_roh_length_df$country <- country_pop

# add colours column 
mean_roh_length_df$colour <- colour_pop

# arrange by colour first (as this corresponds with nhm or modern day) then by population
mean_roh_length_df <- mean_roh_length_df[order(mean_roh_length_df$colour, mean_roh_length_df$pop), ]


# remove DNA damaged samples #

mean_roh_length_df <- mean_roh_length_df %>%
  filter(colour != "black")

# creates a group column corresponding to the colour
# had to delete a failed attempt at creating the group column first
# added column group as a factor due to previous plotting success with this

# add group column to the dataframe

mean_roh_length_df$group <- NA

# group rows by colour column

mean_roh_length_df <- mean_roh_length_df %>%
  select(-group) %>%
  mutate(
    group = case_when(
      colour == "#556B2F" ~ "Modern_Brock_Lynd",
      colour == "#999999" ~ "Modern_other",
      colour == "#E7298A" ~ "Historic_Brock_Lynd",
      TRUE ~ NA_character_
    ),
    group = factor(
      group,
      levels = c(
        "Modern_Brock_Lynd",
        "Modern_other",
        "Historic_Brock_Lynd"
      )
    )
  )



### mean ROH boxplot standard whikser 1.5 x Q1/Q3 ####

library(ggplot2)

# Ensure groups appear in the desired order
mean_roh_length_df$group <- factor(
  mean_roh_length_df$group,
  levels = c(
    "Modern_Brock_Lynd",
    "Modern_other",
    "Historic_Brock_Lynd"
  )
)

# Publication-quality plot
p <- ggplot(
  mean_roh_length_df,
  aes(x = group, y = mean_roh_length)
) +
  
  # Boxplots
  geom_boxplot(
    aes(fill = colour),
    colour = "black",
    width = 0.55,
    linewidth = 0.9,
    alpha = 0.25,
    outlier.shape = NA
  ) +
  
  # Individual samples
  geom_jitter(
    aes(colour = colour),
    width = 0.10,
    height = 0,
    size = 2.8,
    alpha = 0.9
  ) +
  
  # Use colours specified in the dataframe
  scale_colour_identity() +
  scale_fill_identity() +
  
  # Labels
  labs(
    x = "Group",
    y = "Mean ROH length",
    title = "mean_roh_length for all samples excluding DNA damaged hist"
  ) +
  
  # Publication-style theme
  theme_classic(base_size = 14) +
  
  theme(
    plot.title = element_text(
      size = 16,
      face = "bold",
      hjust = 0.5,
      margin = margin(b = 18)
    ),
    
    axis.title.x = element_text(
      size = 15,
      margin = margin(t = 10)
    ),
    
    axis.title.y = element_text(
      size = 15,
      margin = margin(r = 10)
    ),
    
    axis.text.x = element_text(
      size = 12,
      colour = "black",
      angle = 0,
      hjust = 0.5
    ),
    
    axis.text.y = element_text(
      size = 12,
      colour = "black"
    ),
    
    axis.line = element_line(
      linewidth = 0.8,
      colour = "black"
    ),
    
    axis.ticks = element_line(
      linewidth = 0.7,
      colour = "black"
    ),
    
    plot.margin = margin(
      t = 15,
      r = 15,
      b = 15,
      l = 15
    )
  )

p



### mean roh boxplot min max whiskers for greater visualisation ##


p2 <- ggplot(
  mean_roh_length_df,
  aes(x = group, y = mean_roh_length)
) +
  
  geom_boxplot(
    aes(fill = colour),
    colour = "black",
    width = 0.55,
    linewidth = 0.9,
    alpha = 0.25,
    outlier.shape = NA
  ) +
  
  # Explicit whiskers
  stat_summary(
    fun.min = min,
    fun.max = max,
    geom = "errorbar",
    width = 0.18,
    linewidth = 0.9,
    colour = "black"
  ) +
  
  stat_summary(
    fun.min = min,
    fun.max = max,
    geom = "linerange",
    linewidth = 0.9,
    colour = "black"
  ) +
  
  geom_jitter(
    aes(colour = colour),
    width = 0.10,
    height = 0,
    size = 2.8,
    alpha = 0.9
  ) +
  
  scale_colour_identity() +
  scale_fill_identity() +
  
  labs(
    x = "Group",
    y = "Mean ROH length",
    title = "mean_roh_length for all samples excluding DNA damaged hist"
  ) +
  
  theme_classic(base_size = 14) +
  
  theme(
    plot.title = element_text(
      size = 16,
      face = "bold",
      hjust = 0.5,
      margin = margin(b = 18)
    ),
    axis.title.x = element_text(size = 15, margin = margin(t = 10)),
    axis.title.y = element_text(size = 15, margin = margin(r = 10)),
    axis.text.x = element_text(size = 12, colour = "black"),
    axis.text.y = element_text(size = 12, colour = "black"),
    axis.line = element_line(linewidth = 0.8),
    axis.ticks = element_line(linewidth = 0.7),
    plot.margin = margin(15, 15, 15, 15)
  )

p2



#A key component for some of the following analyses, is to calculate the total autosomal length. As 
#we may have filtered some windows out, this could be different from the original length of the genome.


auto <- list()

for (sample in whole_genome_list) {
  
  callable_genome <- get(sample)
  
  autosomal_genome <- sum((callable_genome$window_size)/1000000)
  
  new_name <- if (grepl("^[0-9]", sample)) paste0("V_", sample) else sample
  
  auto[[paste0(new_name, "_length")]] <- autosomal_genome
}

average_genome_length <- mean(unlist(auto))

# if average_genome_length matches up with autosomal_genome then everything is correct

# it matches!


### FROH

#FROH, which stands for “Fraction of the Genome in Runs of Homozygosity,” is a measure used in genetics to estimate the level of inbreeding in an individual. 
#It is calculated as the sum of the length of all ROHs divided by the total autosomal length of the genome. 

# create empty vector to store FROH values
froh_vector <- c()

# loop over each samples
for (sample in sample_names){
  # read in ROH counts variable
  roh_count <- get(paste0(sample, "_ROHOUT"))
  
  # read in the whole genome variable
  genome <- get(paste0(sample, "_whole_genome"))
  
  # calculate FROH
  froh <- sum(roh_count$ROH_Length_MB) / average_genome_length
  
  # assign FROH value
  assign(paste0(sample, "_froh"), froh)
  
  # store FROH values in vector
  froh_vector <- c(froh_vector, froh)
}

# assemble dataframe for froh values
froh_df <- data.frame(sample = sample_names, 
                      froh = froh_vector)

# remove loop variables
remove(sample)
remove(roh_count)
remove(genome)
remove(froh)
remove(froh_vector)




# We than explored some of the relationship among the metrics. 
# For example, we looked at the relationship between FROH and heterozygosity. 

# merge the  dataframes
het_froh_df <- merge(het_kb_df, 
                     froh_df, 
                     by = "sample")

# add vector of shapes 
het_froh_df$shape <- shape_pop


# plot FROH vs AvGWH with ROHs

par(mar = c(5, 5, 4, 7))


plot(het_froh_df$het, het_froh_df$froh, 
     xlab = "Het. pos. per kb", 
     ylab = "FROH",
     main = "FROH vs Het. pos. per kb. Vipera. nhm. mod",
     col = het_froh_df$colour,
     cex = 1.5,
     lwd = 2,
     pch = het_froh_df$shape)



# add subtitle
mtext("50kb windows - 100kb minimum ROH (10 het. pos.)", side = 3, line = 0.5, cex = 0.8)

#add legend with population


legend("topright",
       inset = c(-0.53, 0),   # move legend into the right margin
       xpd = TRUE,            # allow drawing outside plot region
       legend = c("Mod_other", "Mod_bro_lyn", "Hist_bro_lyn", "DNA_damage"),
       col = c("#999999", "#556B2F", "#E7298A", "black"),
       pch = c(1, 2, 0, 0),
       pt.cex = 1.4,
       cex = 1.1,
       x.intersp = 0.4,
       y.intersp = 0.9,
       bty = "n")


#We also checked the relationship between the mean length of ROH and FROH

# At this point I changed the shape value's within the shape variable during "genetic_health" workthrough
# this means that the shape value in the shape variable will not match up to previously generated graph shapes
# (this information could be important for methodology write up)


# merge dataframe 
mean_roh_froh_df <- merge(mean_roh_length_df, 
                          froh_df, 
                          by = "sample")



# remove DNA damaged samples from shape_pop
# data rows missaligned through removal in later steps







# add shape vector
mean_roh_froh_df$shape <- shape_pop


# organise by colour and then pop 
mean_roh_froh_df <- mean_roh_froh_df[order(mean_roh_froh_df$colour, mean_roh_froh_df$pop), ]


# plot FROH against mean length of ROH

# test


library(ggplot2)
library(grid)

ggplot(
  mean_roh_froh_df,
  aes(
    x = mean_roh_length,
    y = froh,
    shape = group,
    colour = group
  )
) +
  geom_point(
    size = 3.2,
    stroke = 0.8
  ) +
  scale_shape_manual(
    values = c(
      "Modern_Brock_Lynd"   = 2,
      "Modern_other"        = 1,
      "Historic_Brock_Lynd" = 0
    )
  ) +
  scale_colour_manual(
    values = c(
      "Modern_Brock_Lynd"   = "#556B2F",
      "Modern_other"        = "#999999",
      "Historic_Brock_Lynd" = "#E7298A"
    )
  ) +
  labs(
    title = "FROH vs Mean ROH length for all samples excluding DNA damaged hist",
    x = "Mean ROH length",
    y = "FROH",
    colour = NULL,
    shape = NULL
  ) +
  theme_classic(base_size = 14) +
  theme(
    # Main title
    plot.title = element_text(
      size = 11,
      face = "plain",
      hjust = 0.5,
      margin = margin(b = 8)
    ),
    
    # Axis titles
    axis.title = element_text(
      size = 14,
      colour = "black"
    ),
    
    # Axis text
    axis.text = element_text(
      size = 12,
      colour = "black"
    ),
    
    # Tick marks
    axis.ticks = element_line(
      colour = "black",
      linewidth = 0.5
    ),
    axis.ticks.length = unit(0.2, "cm"),
    
    # Horizontal legend below plot
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.justification = "center",
    legend.box = "horizontal",
    legend.key = element_blank(),
    
    # Compact legend
    legend.text = element_text(size = 10),
    legend.key.size = unit(0.45, "cm"),
    legend.spacing.x = unit(8, "pt"),
    legend.margin = margin(t = 4, b = 0),
    
    # Small margins so plotting area occupies most of figure
    plot.margin = margin(
      t = 5,
      r = 8,
      b = 5,
      l = 8,
      unit = "pt"
    )
  )




# We can use the length of ROHs to assess the demographic history of the population. In fact, 
# recombination is expected to break down ROHs over time, so the length of ROHs can be used to infer the demographic history of a population. 

# We start by calculating the length of ROH in each of the length categories within ROHCOUNT files. 

# list samples 
roh_list <- ls(pattern = "ROHCOUNT")

# reorder to match sample names
roh_list <- roh_list[match(sample_names, str_remove(roh_list, "_ROHCOUNT"))]

# loop over the list of ROHCOUNT files
for (rohcount in roh_list) {
  
  # read the ROH count data
  roh_data <- get(rohcount)
  
  # calculate the total ROH length in MB 
  roh_data <- roh_data %>%
    mutate(total_length_mb = (ROH_Length_MB * count))
  
  # add the result to the environment
  assign(rohcount, roh_data)
  
}

# remove loop variables
remove(rohcount)
remove(roh_data)

# show structure as an example using the h9d sample to investigate
head(h9d_ROHCOUNT, 10)



#Then we classified the ROHs according to different length categories:

# extra short ROHs (sROH 0.1 - 0.2 Mbp),
# short ROHs (sROH 0.2 - 0.5 Mbp),
# medium ROHs (mROH 0.5 - 1 Mbp),
# long ROHs (lROH > 1 Mbp)

# create function to classify ROHs into length categories
# calculate total count and total length of ROHs in each category
# this function includes the lowe bound not the upper bound (from 100-200, includes 100 but not 200)

classifyROH <- function(input_data) {
  input_data <- input_data %>%
    mutate(ROH_Category = case_when(
      ROH_Length_MB >= 0.1 & ROH_Length_MB < 0.2 ~ "xROH", # discard ROHs shorter than 100kb
      ROH_Length_MB >= 0.2 & ROH_Length_MB < 0.5 ~ "sROH",
      ROH_Length_MB >= 0.5 & ROH_Length_MB < 1 ~ "mROH",
      ROH_Length_MB >= 1 ~ "lROH"
    ))
  
  roh_counts <- input_data %>%
    group_by(ROH_Category) %>%
    summarise(total_count = sum(count), 
              total_length_mb = sum(total_length_mb)
    )
  
  return(roh_counts)
}


# loop over the list of ROHCOUNT file
for (genome in roh_list){
  
  # read in ROHCOUNT file
  rohcount <- get(genome)
  
  # classify ROH length category 
  rohcount_category <- classifyROH(rohcount)
  
  # assign to variable
  assign(paste0(genome, "_category"), rohcount_category)
}

# remove loop variables
remove(genome)
remove(rohcount)
remove(rohcount_category)

# show structure of the file
head(h9d_ROHCOUNT_category)


#At this point, we calculated FROH per each length category. 
#As before, this is done by dividing the total length of ROHs by the total length of the genome. 

# calculate FROH per ROH category
roh_category <- ls(pattern = "ROHCOUNT_category") 

# reorder to match sample names
roh_category <- roh_category[match(sample_names, str_remove(roh_category, "_ROHCOUNT_category"))]

# loop over the list of category files
for (genome in roh_category) {
  
  # read the ROH count data
  roh_length <- get(genome)
  
  # calculate FROH 
  roh_length <- roh_length %>%
    mutate(froh = (total_length_mb / average_genome_length))
  
  # add the result to the environment
  assign(genome, roh_length)
  
}

# remove loop variables
remove(genome)
remove(roh_length)

# show structure of the file
head(h9d_ROHCOUNT_category)



#Create a datframe with ROH length categories and realtive FROH values.


# create empty list 
roh_length_list <- list()

for (sample_roh in roh_category ) {
  # read the ROH count data
  roh_length <- get(sample_roh)
  
  # create dataframe with columns for each ROH length categories
  sample_roh_df <- data.frame(
    xROH = ifelse("xROH" %in% roh_length$ROH_Category, roh_length$total_count[roh_length$ROH_Category == "xROH"], 0),
    sROH = ifelse("sROH" %in% roh_length$ROH_Category, roh_length$total_count[roh_length$ROH_Category == "sROH"], 0),
    mROH = ifelse("mROH" %in% roh_length$ROH_Category, roh_length$total_count[roh_length$ROH_Category == "mROH"], 0),
    lROH = ifelse("lROH" %in% roh_length$ROH_Category, roh_length$total_count[roh_length$ROH_Category == "lROH"], 0)
  )
  
  # add froh per each category 
  sample_roh_df$froh_xROH <- ifelse("xROH" %in% roh_length$ROH_Category, roh_length$froh[roh_length$ROH_Category == "xROH"], 0)
  sample_roh_df$froh_sROH <- ifelse("sROH" %in% roh_length$ROH_Category, roh_length$froh[roh_length$ROH_Category == "sROH"], 0)
  sample_roh_df$froh_mROH <- ifelse("mROH" %in% roh_length$ROH_Category, roh_length$froh[roh_length$ROH_Category == "mROH"], 0)
  sample_roh_df$froh_lROH <- ifelse("lROH" %in% roh_length$ROH_Category, roh_length$froh[roh_length$ROH_Category == "lROH"], 0)
  
  # remove "_ROHCOUNT" from the sample name
  sample_name <- sub("_ROHCOUNT_category", "", sample_roh)
  
  # add sample name as row
  rownames(sample_roh_df) <- sample_name
  
  # add  result in the list
  roh_length_list[[sample_name]] <- sample_roh_df
}

# remove loop variables
remove(roh_length) 
remove(sample_roh_df)
remove(sample_name)

# combine into a single dataframe
roh_length_all <- do.call(rbind, roh_length_list) 


# add colour column as this differentiates by poulation instead of the individals (pop)
roh_length_all$colour <- colour_pop


# add population column
roh_length_all$population <- pop

# arrange by colour first (need to avoid alphabetical issues with next step)
roh_length_all <- roh_length_all[order(roh_length_all$colour, roh_length_all$population), ]

# add group column to the dataframe


roh_length_all$group <- NA

# group rows by colour column

roh_length_all <- roh_length_all %>%
  select(-group) %>%
  mutate(
    group = case_when(
      colour == "#556B2F" ~ "Modern_Brock_Lynd",
      colour == "#999999" ~ "Modern_other",
      colour == "#E7298A" ~ "Historic_Brock_Lynd",
      TRUE ~ NA_character_
    ),
    group = factor(
      group,
      levels = c(
        "Modern_Brock_Lynd",
        "Modern_other",
        "Historic_Brock_Lynd"
      )
    )
  )


# remove DNA damaged samples 

roh_length_all <- roh_length_all %>%
  filter(group != "NA")




## Now plot the FROH values for each ROH length category using a stacked barplot. 

# extract the labels from the first column
labels <- roh_length_all$population

# isolate FROH data
froh_data <- roh_length_all[, grep(
  "froh_", names(roh_length_all))]

# transpose dataframe for plotting
froh_data_long <- t(froh_data)

# this section is just to make the plot look nice
# sum columns of the dataframe
sum_col <- colSums(froh_data_long)

# get the maximum summed value for ylim
max_sum_value <- max(sum_col)



# plotting stacked barplot of FROH
# figure legend added manually afterwards

# Group colours for individual labels
group_cols <- c(
  "Modern_Brock_Lynd"   = "#556B2F",
  "Modern_other"        = "#999999",
  "Historic_Brock_Lynd" = "#E7298A"
)

# Individual names and groups
labels <- roh_length_all$population
group  <- roh_length_all$group


# Create matrix of FROH values

froh_data_long <- t(
  roh_length_all[, c(
    "froh_xROH",
    "froh_sROH",
    "froh_mROH",
    "froh_lROH"
  )]
)

rownames(froh_data_long) <- c(
  "xROH",
  "sROH",
  "mROH",
  "lROH"
)


# Graphical parameters

par(
  # Reduced bottom margin to maximise plotting area
  mar = c(5.5, 5.2, 4.0, 1.0),
  
  mgp = c(2.8, 0.7, 0),
  
  las = 1,
  tcl = -0.3,
  
  bty = "l"
)


# Main stacked barplot

x_axis <- barplot(
  froh_data_long,
  
  beside = FALSE,
  space = 0,
  
  # ROH category colours
  col = c(
    "#007F7F",
    "#F0E442",
    "#56B4E9",
    "#882255"
  ),
  
  # Thin black outlines
  border = "black",
  lwd = 0.5,
  
  ylab = "FROH",
  xlab = "Individual",
  
  xaxt = "n",
  
  main = paste(
    "FROH length and occurrence across the whole genome",
    "of all samples excluding DNA damaged hist"
  ),
  
  cex.main = 0.85,
  font.main = 1,
  
  ylim = c(
    0,
    max(colSums(froh_data_long)) * 1.12
  )
)


# Individual sample labels
# Bold and coloured according to group

text(
  x = x_axis,
  
  # Position labels close beneath the x-axis
  y = par("usr")[3] -
    0.008 * diff(par("usr")[3:4]),
  
  labels = labels,
  
  col = group_cols[group],
  
  srt = 35,
  
  adj = 1,
  
  xpd = TRUE,
  
  cex = 0.95,
  
  font = 2
)
```
